@hostname = http://localhost
@port = 5215

### Get all tasks
GET {{hostname}}:{{port}}/tasks/
Accept: application/json

### Get the health status of the API
GET {{hostname}}:{{port}}/health
Accept: application/json

### Get the OpenAPI specification
GET {{hostname}}:{{port}}/openapi/v1.json
